insert into member_jpa(user_id,user_pw,user_name,user_tel) values('admin1','hi1212','kim1','010-0000-1111');
insert into member_jpa(user_id,user_pw,user_name,user_tel) values('admin2','hi1212','kim1','010-0000-1111');
insert into member_jpa(user_id,user_pw,user_name,user_tel) values('admin3','hi1212','kim1','010-0000-1111');
insert into member_jpa(user_id,user_pw,user_name,user_tel) values('admin4','hi1212','kim2','02-222-2222');
insert into member_jpa(user_id,user_pw,user_name,user_tel) values('admin5','hi1212','lee3','031-3131-3131');
insert into member_jpa(user_id,user_pw,user_name,user_tel) values('tester1','hi1212','lee3','031-3131-3131');
insert into member_jpa(user_id,user_pw,user_name,user_tel) values('tester2','hi1212','lee3','031-3131-3131');
insert into member_jpa(user_id,user_pw,user_name,user_tel) values('tester3','hi1212','kim2','02-222-2222');
insert into member_jpa(user_id,user_pw,user_name,user_tel) values('tester4','hi1212','kim2','02-222-2222');
insert into member_jpa(user_id,user_pw,user_name,user_tel) values('tester5','hi1212','lee3','031-3131-3131');
insert into member_jpa(user_id,user_pw,user_name,user_tel,regdate) values('user1','hi1212','lee3','031-3131-3131',null);
insert into member_jpa(user_id,user_pw,user_name,user_tel,regdate) values('user2','hi1212','lee3','031-3131-3131',now());
insert into member_jpa(user_id,user_pw,user_name,user_tel,regdate) values('user3','hi1212','lee3','031-3131-3131',now());
insert into member_jpa(user_id,user_pw,user_name,user_tel,regdate) values('user4','hi1212','lee3','031-3131-3131',now());
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld1', 'Content for post 1', 'kim1');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld2', 'Content for post 2', 'kim2');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld3', 'Content for post 3', 'kim3');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld4', 'Content for post 4', 'kim4');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld5', 'Content for post 5', 'kim5');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld6', 'Content for post 6', 'kim6');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld7', 'Content for post 7', 'kim7');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld8', 'Content for post 8', 'kim8');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld9', 'Content for post 9', 'kim9');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld10', 'Content for post 10', 'kim10');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld11', 'Content for post 11', 'kim1');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld12', 'Content for post 12', 'kim2');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld13', 'Content for post 13', 'kim3');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld14', 'Content for post 14', 'kim4');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld15', 'Content for post 15', 'kim5');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld16', 'Content for post 16', 'kim6');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld17', 'Content for post 17', 'kim7');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld18', 'Content for post 18', 'kim8');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld19', 'Content for post 19', 'kim9');
INSERT INTO board_jpa (title, content, writer) VALUES ('HelloWorld20', 'Content for post 20', 'kim10');
